config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "bookmarks/search", controller: :bookmarks, action: :search, as: :bookmarks_search
  get "bookmarks/tagged_with/:tags", controller: :bookmarks, action: :tagged_with, as: :bookmarks_tagged_with
  get "bookmarks/unarchived", controller: :bookmarks, action: :unarchived, as: :bookmarks_unarchived
  get "bookmarks/to_read", controller: :bookmarks, action: :to_read, as: :bookmarks_to_read

  # a trivially small success page which expects to be closed immediately
  # by the plugin
  get "bookmarks/success", controller: :bookmarks, action: :success, as: :bookmarks_success
  get "bookmarks/:id/archive", controller: :bookmarks, action: :archive, as: :bookmarks_archive, via: [:post, :put]

  resources :bookmarks do
    member do
      put "archive"
      get "download"
      put "mark_as_read"
      put "mark_to_read"
    end
  end

  resources :settings
  resources :tags

  get "importer", controller: :importer, action: :index, as: :importer_form
  post "importer/import", controller: :importer, action: :import, as: :importer_import


  # Defines the root path route ("/")
  root "bookmarks#index"


  match "/debugging/echo" => "debugging#echo", via: [:get, :post, :put, :patch, :delete]
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # ⚠ WARNING TO FUTUTRE HACKERS
  # The user privacy stuff in here is based on the idea that
  # there will only be one user.
  # It is guaranteed to expose private data if
  # you allow multiple accounts to be created.
  # Don't do that. This is a single-user instance.

  before_action :set_bookmark, only: %i[show download edit update archive destroy]
  before_action :set_limit, only: %i[index tagged_with search unarchived to_read]
  before_action :set_page, only: %i[index tagged_with search unarchived to_read]
  before_action :set_closeable, only: %i[new edit create update show]
  before_action :set_archive, only: %i[show download]
  before_action :set_total_bookmarks, only: %i[index unarchived to_read tagged_with search]
  before_action :authenticate_user!, only: %i[new create update destroy archive mark_as_read mark_to_read]

  # GET /bookmarks or /bookmarks.json
  def index
    query = Bookmark.all.order_by([[:created_at, :desc]])
    query = add_tags_to_query_and_view(params[:tags], query,
      include_tags_list: params[:tags].present?)
    if params[:tags].blank?
      @tags_list = Tag.all
        .order_by([[:name, :asc]])
        .pluck(:name)
        .map { |t| helpers.decode_entities(t) }
    end
    query = privatize(query)

    @pagy, @bookmarks = pagify(query)
  end

  def unarchived
    query = Bookmark.unarchived
      .order_by([[:created_at, :desc]])
    query = add_tags_to_query_and_view(params[:tags], query)
    query = privatize(query)
    @pagy, @bookmarks = pagify(query)
    render :index
  end

  def to_read
    query = Bookmark.to_read
      .order_by([[:created_at, :desc]])

    query = add_tags_to_query_and_view(params[:tags], query)

    query = privatize(query)
    @pagy, @bookmarks = pagify(query)
    render :index
  end

  def tagged_with
    @tags = params[:tags].split(",")
    if @tags.blank?
      flash_message(:notice, t("tags.errors.no_tags_provided"))
      redirect_to :index
      return
    end

    tagged_with_criteria = Bookmark.tagged_with_all(@tags)
    @tags_list = tagged_with_criteria.pluck(:tags).flatten.sort.uniq
    @pagy, @bookmarks = pagify(
      privatize(
        tagged_with_criteria
        .order_by([[:created_at, :desc]])
      )
    )

    @tags_list = @tags_list.map { |t| helpers.decode_entities(t) }
    render :index
  end

  def search
    @query = params[:query]
    if @query.blank?
      flash_message(:notice, t("search.missing_query"))
      redirect_to action: "index"
      return
    end

    # configure sorting
    sort_params = []
    @sort = params[:sort] || "match"
    if @sort == "newest"
      sort_params << "created_at:desc"
    end

    # Meilisearch Options
    options = {
      limit: @limit,
      sort: sort_params,
      offset: (@limit * (@page - 1)) # number of resources skipped
    }
    unless user_signed_in?
      options[:filter] = "private = false"
    end

    if params[:tags].present?
      @tags = params[:tags].split(",")
      options = add_tags_to_search_options(@tags, options)
    end

    begin
      # if we were searching for _any_ record we'd use `filtered_by_class: false`
      # note: already privatized via filter
      # raw_results is a hash see the following for details
      # https://github.com/masukomi/mongodb_meilisearch?tab=readme-ov-file#searching
      raw_results = Bookmark.search(@query,
        options: options,
        ids_only: true,
        filtered_by_class: true)
      @bookmarks = Bookmark.where(:id.in => raw_results["matches"])
      if @tags&.present?
        # in theory, this is redundant because the search criteria
        # would have filtered on tags BUT I'd rather be sure
        @bookmarks = @bookmarks.tagged_with_all(@tags)
      end

      @tags_list = @bookmarks.pluck(:tags).flatten.sort.uniq
      @pagy      = pagify_search(raw_results["search_result_metadata"]["nbHits"])

      render :index
    rescue MeiliSearch::ApiError => e
      if e.message.include?("Index `backup_brain_general` not found")
        if Bookmark.count > 0
          flash_message(:notice, t("search.missing_index"))
        else
          flash_message(:notice, t("search.no_bookmarks"))
        end
      elsif e.message.include?("The provided API key is invalid")
        search_key = ENV.fetch("MEILISEARCH_SEARCH_KEY", nil)
        admin_key = ENV.fetch("MEILISEARCH_ADMIN_KEY", nil)
        if search_key.present? && admin_key.present?
          flash_message(:error, t("search.invalid_api_key"))
        else
          flash_message(:error, t("search.invalid_master_api_key"))
        end
      else
        flash_message(:error, t("search.unknown_error", error: e.message))
      end
      redirect_to bookmarks_path
    end
  end

  # GET /bookmarks/1 or /bookmarks/1.json
  def show
    # set_archive is invoked before this
  end

  def download
    # set_archive is invoked before this
    mime_type = @archive.mime_type || "text/markdown"
    filename = (@bookmark.title || "bookmark")
      .downcase
      .gsub(/\W+/, "_")
      .sub(/_*$/, "") + ".md"
    send_data(@archive.string_data,
      type: mime_type,
      filename: filename,
      disposition: "attachment")
  end

  # GET /bookmarks/new
  def new
    if params[:url].present?
      @bookmark = Bookmark.where(url: params[:url]).first
    end
    if @bookmark.present?
      flash_message(:notice, t("bookmarks.create_existing_warning"))
      redirect_to edit_bookmark_url(@bookmark, layout: @layout, closeable: @closeable)
      return
    end
    url = params[:url].strip if params[:url].present?
    title = params[:title].strip if params[:title].present?
    description = params[:description].strip if params[:description].present?

    @bookmark = Bookmark.new(url: url, title: title, description: description)
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks or /bookmarks.json
  def create
    @bookmark = Bookmark.new(split_tag_params)
    @bookmark.user = current_user

    respond_to do |format|
      if @bookmark.save
        format.html {
          flash_message(:notice, t("bookmarks.creation_success"))
          if @closeable.present?
            redirect_to bookmarks_success_path(layout: @layout, closeable: @closeable)
          else
            redirect_to bookmarks_path
          end
        }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT
  def archive
    updated_bookmark = @bookmark.generate_archive(true)
    @bookmark = updated_bookmark || @bookmark.reload

    respond_to do |format|
      format.turbo_stream {
        if updated_bookmark
          inline_flash_message(:notice, t("bookmarks.archiving_success"))
        else
          inline_flash_message(:error, t("bookmarks.archiving_error"))
        end
        render turbo_stream: turbo_stream.replace(
          @bookmark,
          partial: "bookmark",
          locals: {
            bookmark: @bookmark,
            inline_flash: @inline_flash
          }
        )
      }

      format.html {
        if updated_bookmark
          flash_message(:notice, t("bookmarks.archiving_success"))
        else
          flash_message(:error, t("bookmarks.archiving_error"))
        end
        redirect_to bookmark_url(@bookmark)
      }
    end
  end

  # PATCH/PUT
  def mark_as_read
    set_to_read(false)
  end

  # PATCH/PUT
  def mark_to_read
    set_to_read(true)
  end

  # PATCH/PUT /bookmarks/1 or /bookmarks/1.json
  def update
    respond_to do |format|
      # FIXME: there's got to be a better way to do this than my split_tag_params
      if @bookmark.update(split_tag_params)
        format.html {
          flash_message(:notice, t("bookmarks.update_success"))
          if @closeable.present?
            redirect_to bookmarks_success_path(layout: @layout, closeable: @closeable)
            # redirect_to bookmarks_success_path, layout: @layout
          else
            redirect_to bookmarks_path, notice: t("bookmarks.update_success")
          end
        }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1 or /bookmarks/1.json
  def destroy
    @bookmark.destroy

    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: turbo_stream.replace(
          @bookmark,
          partial: "removed_bookmark",
          locals: {bookmark: @bookmark}
        )
      }
      format.html { redirect_to bookmarks_url, notice: t("bookmarks.deletion_success") }
      format.json { head :no_content }
    end
  end

  def success
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.private? && !user_signed_in?
      @bookmark = nil
      flash_message(:error, t("accounts.access_denied"))
      redirect_to bookmarks_url
    end
  end

  # Only allow a list of trusted parameters through.
  def bookmark_params
    params.require(:bookmark).permit(:title, :url, :description, :tags, :private, :to_read)
  end

  def split_tag_params
    unsplit_tags = params.dig(:bookmark, :tags)
    tags = Tag.split_tags(unsplit_tags)
    bookmark_params.merge({tags: tags})
  end

  def set_limit
    @limit = params[:limit].present? ? params[:limit].to_i : Pagy::DEFAULT[:items]
  end

  def set_page
    @page = params[:page].present? ? params[:page].to_i : 1
  end

  def pagify(query, page = @page, limit = @limit)
    paginated_query = query.paginate(page: page, limit: limit)
    [
      Pagy.new(count: query.count, page: page, items: limit),
      paginated_query
    ]

app/helpers/bookmarks_helper.rb
module BookmarksHelper
  def show_archive_link(archive)
    link_to(
      archive_date_string(archive),
      bookmark_path(archive.bookmark, archive_id: archive._id.to_s)
    )
  end

  def archive_date_string(archive)
    I18n.l(archive.created_at.to_date, format: :default)
  end

  def get_joined_tags(tags)
    tags.nil? ? "" : tags.join(",")
  end

  # TODO: there's a bunch of code below that can be
  # refactored into common methods

  def get_pagination_links_for_query(pagy:, query:, limit:, tags:)
    joined_tags = get_joined_tags(tags)
    link = proc { |pagy, link_extra|
      link_to(
        pagy,
        bookmarks_search_path(page: pagy,
          limit: limit,
          query: query,
          tags: joined_tags),
        method: :get,
        class: "page-link",
        aria_label: I18n.t("pagination.aria_next")
      )
    }

    previous_link = link_to(
      t("pagination.previous"),
      bookmarks_search_path(page: pagy.prev,
        limit: limit,
        query: query,
        tags: joined_tags),
      method: :get,
      class: "page-link",
      aria_label: I18n.t("pagination.aria_previous")
    )
    next_link = link_to(
      t("pagination.next"),
      bookmarks_search_path(
        page: pagy.next,
        limit: limit,
        query: query,
        tags: joined_tags
      ),
      method: :get,
      class: "page-link",
      aria_label: I18n.t("pagination.aria_next")
    )
    {
      link_proc: link,
      previous_link: previous_link,
      next_link: next_link
    }
  end

  def get_pagination_links_for_unread(pagy:, limit:, tags:)
    joined_tags = get_joined_tags(tags)
    link = proc { |pagy, link_extra|
      link_to(
        pagy,
        bookmarks_to_read_path(page: pagy,
          limit: limit,
          tags: joined_tags),
        method: :get,
        class: "page-link",
        aria_label: I18n.t("pagination.aria_next")
      )
    }
    previous_link = link_to(
      t("pagination.previous"),
      bookmarks_to_read_path(page: pagy.prev,
        limit: limit,
        tags: joined_tags),
      method: :get,
      class: "page-link",
      aria_label: I18n.t("pagination.aria_previous")
    )
    next_link = link_to(
      t("pagination.next"),
      bookmarks_to_read_path(page: pagy.next,
        limit: limit,
        tags: joined_tags),
      method: :get,
      class: "page-link",
      aria_label: I18n.t("pagination.aria_next")
    )
    {
      link_proc: link,
      previous_link: previous_link,
      next_link: next_link
    }
  end

  def get_pagination_links_for_unarchived(pagy:, limit:, tags:)
    joined_tags = get_joined_tags(tags)
    link = proc { |pagy, link_extra|
      link_to(
        pagy,
        bookmarks_unarchived_path(page: pagy,
          limit: limit,
          tags: joined_tags),
        method: :get,
        class: "page-link",
        aria_label: I18n.t("pagination.aria_next")
      )
    }
    previous_link = link_to(
      t("pagination.previous"),
      bookmarks_unarchived_path(page: pagy.prev,
        limit: limit,
        tags: joined_tags),
      method: :get,
      class: "page-link",
      aria_label: I18n.t("pagination.aria_previous")
    )
    next_link = link_to(
      t("pagination.next"),
      bookmarks_unarchived_path(page: pagy.next,
        limit: limit,
        tags: joined_tags),
      method: :get,
      class: "page-link",
      aria_label: I18n.t("pagination.aria_next")
    )
    {
      link_proc: link,
      previous_link: previous_link,
      next_link: next_link
    }
  end

  def get_pagination_links_for_default(pagy:, limit:, tags:)
    joined_tags = get_joined_tags(tags)
    link = proc { |pagy, link_extra|
      link_to(
        pagy,
        bookmarks_path(page: pagy,
          limit: limit,
          tags: joined_tags),
        method: :get,
        class: "page-link",
        aria_label: I18n.t("pagination.aria_next")
      )
    }
    previous_link = link_to(
      t("pagination.previous"),
      bookmarks_path(page: pagy.prev,
        limit: limit,
        tags: joined_tags),
      method: :get,
      class: "page-link",
      aria_label: I18n.t("pagination.aria_previous")
    )
    next_link = link_to(
      t("pagination.next"),
      bookmarks_path(page: pagy.next,
        limit: limit,
        tags: joined_tags),
      method: :get,
      class: "page-link",
      aria_label: I18n.t("pagination.aria_next")
    )
    {
      link_proc: link,
      previous_link: previous_link,
      next_link: next_link
    }
  end
end

app/views/bookmarks/_bookmark.html.erb
<% privacy_class = (bookmark.private? ? 'private-bookmark' : '')
   to_read_class = (bookmark.to_read? ? 'to-read-list-item' : '')
   %>
<div id="<%= dom_id bookmark %>" class="container bookmark-list-item <%= privacy_class %> <%= to_read_class %>">
  <div class="row">
    <div class="col">
      <% if defined?(inline_flash) %>
        <%= render partial: 'shared/inline_flash',
            locals: {inline_flash: inline_flash} %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-8">

      <%# favicon %>
      <div class="row">
        <div class="col">
          <% if get_setting('enable_favicons') == true %>
            <% if bookmark.domain.present? %>
              <img class="favicon"
                  src="<%= request.protocol %>www.google.com/s2/favicons?sz=64&domain=<%= bookmark.domain %>" />
            <% else %>
              <%= inline_icon("missing_image", icon_class: "favicon") %>
            <% end %>
          <% end %>
          <%= link_to(bookmark.title, bookmark.url) %>
        </div>
      </div>

      <%# description %>
      <div class="row">
        <div class="col">
          <% if bookmark.description.present? %>
            <%== ::Rendering::Markdown.instance.render(bookmark.description) %>
          <% else %>
            &nbsp;
          <% end %>
        </div>
      </div>

      <%# tags %>
      <div class="row">
        <div class="col">
          <%= render partial: 'shared/inline_tag_list',
              locals: {tags: bookmark.tags} %>
        </div>
      </div>

    </div> <%# end col-8 main bookmark section %>

    <!--- action icons -->
    <div class="col">
      <div class="action-icons">
        <!-- archive action -->
        <% if bookmark.has_archive? %>
          <div class="action-icon">
            <%= icon_link("archive", bookmark_path(bookmark),
                  link_css: "inline-link-icon archive-link-icon",
                  alt: t('bookmarks.view_archive_alt_text'),
                  title: t('bookmarks.view_archive_title',
                          archive_date: I18n.l(bookmark.latest_archive.created_at.to_date,
                                              format: :default)
                  ),
                  text:  t('bookmarks.view_archive_link_text')
                )
                %>
          </div>
        <% elsif bookmark.is_fresh? && ! bookmark.last_archive_attempt_failed? %>
            <%= icon_link("archiving", '#',
                  link_css: "inline-link-icon archive-link-icon",
                  alt: t('bookmarks.archiving_now_alt'),
                  title: t('bookmarks.archiving_now_title'),
                  text:  t('bookmarks.archiving_now_text')
                )
                %>
        <% elsif user_signed_in? %>
          <div class="action-icon archive-action-icon">
            <%== link_to  image_tag(
                '/images/icons/download.svg',
                 class: 'inline-link-icon download-icon'
                 ) +
                 t('bookmarks.archive_now_link_text'),
                  archive_bookmark_path(bookmark, method: :put),
                  class: "inline-link-icon archive-link-icon",
                  method: :put,
                  data:   {
                  turbo_method: :put
                  }

                %>
            <% if bookmark.last_archive_attempt_failed?
               link_details = bookmark.failed_archive_attempts.last.link_details
               %>
              <span class="archive-error-code" >

                <%= link_to(link_details[:status_code],
                    (link_details.fetch(:url, '#')),
                    title: link_details.fetch(:title),
                    target: '_blank') %>
              </span>
            <% end %>
          </div>
        <% end %>

        <% if user_signed_in? %>
        <!-- restricted actions -->
          <!-- edit -->
          <div class="action-icon">
            <%= icon_link("edit", edit_bookmark_path(bookmark),
                link_css: "inline-link-icon edit-link-icon",
                method: :put,
                alt: t('bookmarks.edit'),
                text: t('bookmarks.edit')) %>
          </div>
          <!-- read status toggle -->
          <% if bookmark.to_read? %>
            <div class="action-icon">
              <%== link_to  image_tag(
                              '/images/icons/to_read.svg',
                              class: 'inline-link-icon to-read-icon'
                            ) + t('bookmarks.mark_as_read_link'),
                            mark_as_read_bookmark_path(bookmark, method: :put),
                            class: "inline-link-icon to-read-link-icon",
                    method: :put,
                    data:   {
                      turbo_method: :put,
                    }
                %>

            </div>
          <% else %>
            <div class="action-icon">
              <%== link_to  image_tag(
                            '/images/icons/to_read.svg',
                            class: 'inline-link-icon to-read-link-icon'
                          ) + t('bookmarks.mark_to_read'),
                          mark_to_read_bookmark_path(bookmark, method: :put),
                          class: "inline-link-icon to-read-link-icon",
                  method: :put,
                  data:   {
                    turbo_method: :put,
                  }

                %>
            </div>
          <% end %>

          <!-- privacy reminder -->
          <% if bookmark.private? %>
            <div class="action-icon">
              <%= inline_icon("private", icon_class: "inline-body-icon") %>
              <span class="private-hint"><%=t('bookmarks.private_hint') %></span>
            </div>
          <% end %>

          <!-- delete action -->
          <div class="action-icon delete-action-icon">
            <%== link_to  image_tag(
                '/images/icons/delete.svg',
                class: 'inline-link-icon delete-icon') + t('bookmarks.delete_link'),
                  bookmark_path(bookmark, method: :delete),
                  class: "inline-link-icon delete-link-icon",
                  method: :delete,
                  data:   {
                  confirm: t('misc.are_your_sure'),
                  turbo_method: :delete,
                  turbo_confirm: t('misc.are_you_sure')
                  }

                %>

          </div>
      <% end %> <!-- end requires login -->
      </div> <!-- end action-icons -->
    </div>
  </div>
</div>

app/views/bookmarks/_bookmark_md_archive.html.erb
<%# Note: this exists within a bootstrap 'col' %>
<archive>
<%= ::Rendering::Markdown.instance.render(archive.string_data).html_safe %>
</archive>

app/views/bookmarks/_form.html.erb
<div class="container">
  <%= render partial: 'shared/errors_row', locals: {thing: bookmark} %>
  <%= form_with(model: bookmark) do |form| %>
    <%= hidden_field_tag(:closeable, @closeable) %>
    <%= hidden_field_tag(:layout, @layout) %>

    <div class="row">
      <div class="col-2">
        <%= form.label :url, style: "display: block" %>
      </div>
      <div class="col-9">
        <%= form.text_field :url, class: 'bookmark-input-field'  %>
      </div>
    </div>

    <div class="row">
      <div class="col-2">
        <%= form.label :title, style: "display: block" %>
      </div>
      <div class="col-9">
        <%= form.text_field :title, class: 'bookmark-input-field'  %>
      </div>
    </div>

    <div class="row">
      <div class="col-2">
        <%= form.label :description, style: "display: block" %>
      </div>
      <div class="col-9">
        <%= form.text_area :description, class: 'bookmark-textarea-field' %>
        <div style="float: right;"><%== t('misc.markdown_supported_here') %></div>
      </div>
    </div>

    <div class="row safe-space">
      <div class="col-2">
        <%= form.label :tags, style: "display: block" %>
      </div>
      <div class="col-9">
        <%= form.text_field :tags, class: 'bookmark-input-field' %>
      </div>
    </div>

    <div class="row">
      <div class="col-2">
        <%= form.label :private,
            style: "display: block",
            class: "form-check-label",
            for: "privacySwitch"
            %>
      </div>
      <div class="col-1 form-check form-switch">
        <%= form.check_box :private,
            class: 'bookmark-checkbox-field form-check-input toggle',
            role: "switch",
            id: "privacySwitch",
            checked: bookmark.private?
            %>
      </div>
    </div>

    <div class="row">
      <div class="col-2">
        <%= form.label :to_read,
            style: "display: block",
            class: "form-check-label",
            for: "privacySwitch"
            %>
      </div>
      <div class="col-1 form-check form-switch">
        <%= form.check_box :to_read,
            class: 'bookmark-checkbox-field form-check-input toggle',
            role: "switch",
            id: "toReadSwitch",
            checked: bookmark.to_read?
            %>
      </div>
    </div>
    <div class="row">
      <div class="col ">
        <%= form.submit class: "btn btn-primary" %>
      </div>
    </div>

  <% end %>

</div>

app/views/bookmarks/_list_heading.html.erb
<heading>
  <% if ! defined?(@tags) %>
    <% if action_name == 'index' || action_name == 'search' %>
      <%= t('bookmarks.headings.simple')%>
    <% elsif action_name == 'tagged_with' %>
      <%= t('bookmarks.headings.unread')%>
    <% elsif action_name == 'unarchived' %>
      <%= t('bookmarks.headings.unarchived')%>
    <% elsif action_name == 'to_read' %>
      <%= t('bookmarks.headings.to_read')%>
    <% else %>
      <%= t('bookmarks.headings.simple')%>
    <% end %>
  <% else %>
    <% if action_name == 'index' || action_name == 'search' %>
      <%= t('bookmarks.headings.simple_and_tagged_with', tags: @tags.join(', '))%>
    <% elsif action_name == 'tagged_with' %>
      <%= t('bookmarks.headings.unread_and_tagged_with', tags: @tags.join(', '))%>
    <% elsif action_name == 'unarchived' %>
      <%= t('bookmarks.headings.unarchived_and_tagged_with', tags: @tags.join(', '))%>
    <% elsif action_name == 'to_read' %>
      <%= t('bookmarks.headings.to_read_and_tagged_with', tags: @tags.join(', '))%>
    <% else %>
      <%= t('bookmarks.headings.simple_and_tagged_with', tags: @tags.join(', '))%>
    <% end %>
  <% end %>
</heading>
<% if @total_bookmarks != 0 %>
  <span class="bookmark-count">
  <%= t('bookmarks.counter',
        formatted_count: number_with_delimiter(
                          @pagy.count || @bookmarks.count,
                          delimiter: t('number.format.delimiter')
        )
      ) %>
  </span>
<% end %>

app/views/bookmarks/_removed_bookmark.html.erb
<div id="<%= dom_id bookmark %>" class="container bookmark-list-item deleted">
  <div class="row">
    <div class="col">
      <%= t('bookmarks.inline_deletion_message') %>
    </div>
  </div>
</div>

app/views/bookmarks/show.html.erb
<div class="container">
  <% if @archive.present?  %>
    <div class="row">
      <div class="col">
        <heading><%=link_to(@bookmark.title, @bookmark.url) %></heading>
        <div>
          <%= render partial: 'shared/inline_tag_list',
              locals: {tags: @bookmark.tags} %>

        </div>
        <div class="archive-date">
          <%=t('bookmarks.archived_date_message',
              archive_date: archive_date_string(@archive)
          ) %>

        </div>


        <%#TODO deal with rendering archives that might not be markdown %>
        <%= render partial: 'bookmark_md_archive',
            locals: {archive: @archive} %>
      </div>
    </div>
  <% else %>
    <div class="row alert alert-warning">
      <div class="col">
        <%= t('errors.bookmarks.no_archive_found') %>
      </div>
    </div>
  <% end %>
</div>

<% content_for :sidebar do %>
  <%= render partial: 'shared/sidebar_page_actions_top' %>
  <div id="page-actions">
    <div class="container">
      <div class="row">
        <div class="col">
          <ul>
          <li><%= link_to t('bookmarks.edit_this_link'), edit_bookmark_path(@bookmark),
              class: 'btn btn-primary compact-button' %></li>

          <li><%= link_to t('bookmarks.rearchive_this_link'), archive_bookmark_path(@bookmark),
              class: 'btn btn-primary compact-button' %></li>
          </ul>
        </div>
      </row>
      <div class="row">
        <div class="col">
          <div class="safe-space">
            <%= button_to "Destroy this bookmark", @bookmark,
                method: :delete ,
                class: 'btn btn-danger compact-button'%>
          </div>
        </div>
      </div>
      <!-- archives list -->
      <div class="row">
        <div class="col">
          <em><%= t("bookmarks.archives_list_heading") %></em>
          <ul id="bookmark-archives-listing">
            <% @bookmark.sorted_archives.each do | an_archive |
              current = (an_archive.id == @archive&.id)
              %>
              <li class="<%= current ? 'current-archive-item' : '' %>">
                <%= show_archive_link(an_archive) %>
                <%= icon_link("download",
                      download_bookmark_path(@bookmark, archive_id: @archive._id),
                    link_css: "inline-link-icon download-link-icon",
                    method: :put,
                    alt: t('bookmarks.download_archive_link')) %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="container">
</div>