config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "bookmarks/search", controller: :bookmarks, action: :search, as: :bookmarks_search
  get "bookmarks/tagged_with/:tags", controller: :bookmarks, action: :tagged_with, as: :bookmarks_tagged_with
  get "bookmarks/unarchived", controller: :bookmarks, action: :unarchived, as: :bookmarks_unarchived
  get "bookmarks/to_read", controller: :bookmarks, action: :to_read, as: :bookmarks_to_read

  # a trivially small success page which expects to be closed immediately
  # by the plugin
  get "bookmarks/success", controller: :bookmarks, action: :success, as: :bookmarks_success
  get "bookmarks/:id/archive", controller: :bookmarks, action: :archive, as: :bookmarks_archive, via: [:post, :put]

  resources :bookmarks do
    member do
      put "archive"
      get "download"
      put "mark_as_read"
      put "mark_to_read"
    end
  end

  resources :settings
  resources :tags

  get "importer", controller: :importer, action: :index, as: :importer_form
  post "importer/import", controller: :importer, action: :import, as: :importer_import


  # Defines the root path route ("/")
  root "bookmarks#index"


  match "/debugging/echo" => "debugging#echo", via: [:get, :post, :put, :patch, :delete]
end

app/views/shared/_errors_row.html.erb
  <% if thing.errors.any? %>
    <div class="row">
      <div class="col" style="color: red">
		  <%= t("misc.errors.num_errors_prevented_save",
          number: pluralize(thing.errors.count, "error"),
          thing_type: thing.class.name.humanize) %>
        <ul>
          <% thing.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

app/views/shared/_inline_flash.html.erb
<% inline_flash.each do |type, msg| %>
    <% Array(msg).each do |m| %>
        <div class="alert <%=class_for_flash(type) %>">
            <%= t("misc.alerts.#{type}") %>: <%= m %>
        </div>
    <% end %>
<% end %>

app/views/shared/_inline_tag_list.html.erb
<% if tags.present? %>
    <% tags.each do | tag | %>
        <span class="no-wrap">
            <%= icon_link(
                "tag",
                bookmarks_tagged_with_path(tags: tag),
                link_css: "inline-link-icon",
                alt: t('icons.tag_alt')
            ) %>
            <%= link_to(tag.html_safe, bookmarks_tagged_with_path(tags: tag)) %>
        </span>
    <% end %>
<% else %>
    <span class="quiet-notice"><%= t('bookmarks.no_tags_message') %></span>
<% end %>

app/views/shared/_search_form.html.erb
<%# using css style attribute because something's wrong and the browser is refusing to admit the
    class definition exists in custom.css %>
<div class="search-form" >
  <%= form_with url: bookmarks_search_path, data: {turbo: false}, method: :get do |form| %>
    <%= form.label :query, I18n.t("search.form_label"), class: "screen-readers-only" %>
      <input type="text" name="query" value="<%= query %>" placeholder="<%= t("search.placeholder") %>" >
      <input type="radio" name="sort" value="match"
      <% if ! @sort || @sort == "match" %>checked<% end %>
      id="sort_radio_match" >
      <label for="sort_radio_match" ><%=I18n.t("search.match_sort_label")%></label>
      <input type="radio" name="sort" value="newest"
      <% if @sort == "newest" %>checked<% end %>
      id="sort_radio_newest" >
      <label for="sort_radio_newest" ><%=I18n.t("search.newest_sort_label")%></label>
      <%= form.submit I18n.t("search.search_button"),
          type: :image,
          src: "/images/icons/search_white.svg",
          class: "btn btn-primary compact-button search-go-button" %>
  <% end %>
</div>

app/views/shared/_side_administration.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <hr />
      <ul id="bottom-side-nav-items">
        <% if current_user %>
          <li><div class="vertically-separated">
               <%= icon_link('importing',
                  importer_form_path,
                  text: t('importer.import_link'),
                  alt: t('importer.import_link_icon_alt'),
                  link_css: "inline-link-icon importer-link-icon"
                  ) %>
              </div>
          </li>
          <li><div>
              <%= icon_link('settings',
                  settings_path,
                  text: t('settings.nav_link'),
                  alt: t('settings.icon_alt'),
                  link_css: "inline-link-icon importer-link-icon"
                  ) %>
              </div>
          </li>
        <% end %>
        <li class="file-ticket">
          <div class="vertically-separated">
            <%= icon_link('file_a_ticket',
                "https://github.com/masukomi/backup_brain/issues/new/choose",
                text: t('misc.file_a_ticket'),
                title: t('misc.file_a_ticket_icon_title'),
                alt: t('misc.file_a_ticket_icon_alt'),
                link_css: "inline-link-icon file-a-ticket-link-icon",
                target: '_blank'
                ) %>
          </div>
        </li>
        <li class="support">
           <a href="https://ko-fi.com/backup_brain"
              class="inline-icon-link"
              ><%== t('misc.support_me_link') %></a>
        </li>

      </ul>
    </div>
  </div>
</div>

app/views/shared/_side_navigation.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <ul id="side-nav-items">
        <% unless current_user %>
          <li><span class="learn-more"><a href="https://BackupBrain.app" title="<%= t('misc.learn_more_title')%>"><%==t('misc.learn_more_link')%></a></span></li>
        <% end  %>

        <li><%= link_to t('bookmarks.all_link'), bookmarks_path %>
        <% if current_user %>
          <li><%= link_to t('bookmarks.add'), new_bookmark_path %> </li>
        <% end %>
        <li><%= link_to t('navigation.to_read_link'), bookmarks_to_read_path %></li>
        <li><%= link_to t('navigation.unarchived_link'), bookmarks_unarchived_path %></li>
        <% if current_user %>
        <li><%= link_to t('tags.link'), tags_path %></li>
        <% end %>


        <%# WITH LOGGED IN USER %>
        <% if current_user %>
          <li><%= button_to t('accounts.links.sign_out'), destroy_user_session_path, method: :delete, class: "btn btn-small btn-primary mx-2 compact-button safe-space" %></li>
        <%# WITHOUT LOGIN BUT WITH A USER EXISITNG %>
        <% elsif @user_count > 0 %>
          <li><%= link_to t('accounts.links.sign_in'), new_user_session_path, class: "nav-link"  %></li>
        <%# NEW INSTALL NO USER %>
        <% else %>
          <%# for now we're keeping this a single user app ' %>
          <li><%= link_to t('accounts.links.sign_up'), new_user_registration_path, class: "nav-link"  %></li>
        <% end %>

      </ul>
    </div>
  </div>
</div>

app/views/shared/_side_tags.html.erb
<div class="container">
  <div class="row">
    <div class="col sidebar-tags">
      <% if defined?(@tags) or action_name== 'search' %>
        <div id="tags-list-heading"><%= t('tags.overlapping_tags') %></div>
      <% end %>
      <% @tags_list.each do |tag| %>
        <span class="sidebar-tag">
            <% tags_query_param= defined?(@tags) ? (@tags + [tag]).join(',') : tag %>
            <% if action_name == 'search' %>
              <%= icon_link("add", bookmarks_search_path(query: params[:query], tags: tags_query_param),
                    link_css: "inline-icon-link",
                    icon_css: "add-tag-icon",
                    alt: t('tags.add_tag_to_query'),
                    title: t('tags.add_tag_to_query')
                  ) if @tags
                  %>
              <%= link_to(tag, bookmarks_search_path(query: params[:query], tags: tag)) %>
            <% elsif action_name == 'unarchived' %>
              <%= icon_link("add", bookmarks_unarchived_path(tags: tags_query_param),
                    link_css: "inline-icon-link",
                    icon_css: "add-tag-icon",
                    alt: t('tags.add_tag_to_query'),
                    title: t('tags.add_tag_to_query')
                  ) if @tags
                  %>
              <%= link_to(tag, bookmarks_unarchived_path(tags: tag)) %>
            <% elsif action_name == 'to_read' %>
              <%= icon_link("add", bookmarks_to_read_path(tags: tags_query_param),
                    link_css: "inline-icon-link",
                    icon_css: "add-tag-icon",
                    alt: t('tags.add_tag_to_query'),
                    title: t('tags.add_tag_to_query')
                  ) if @tags
                  %>
              <%= link_to(tag, bookmarks_to_read_path(tags: tag)) %>
            <% else %>
              <%= icon_link("add", bookmarks_tagged_with_path(tags: tags_query_param),
                    link_css: "inline-icon-link",
                    icon_css: "add-tag-icon",
                    alt: t('tags.add_tag_to_query'),
                    title: t('tags.add_tag_to_query')
                  ) if @tags
                  %>
              <%= link_to(tag, bookmarks_tagged_with_path(tags: tag)) %>
            <% end %>
        </span>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_sidebar_page_actions_top.html.erb
<div class="row">
    <div class="col">
        <em><%=t('sidebar.page_actions_header') %></em>
    </div>
</div>