config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "bookmarks/search", controller: :bookmarks, action: :search, as: :bookmarks_search
  get "bookmarks/tagged_with/:tags", controller: :bookmarks, action: :tagged_with, as: :bookmarks_tagged_with
  get "bookmarks/unarchived", controller: :bookmarks, action: :unarchived, as: :bookmarks_unarchived
  get "bookmarks/to_read", controller: :bookmarks, action: :to_read, as: :bookmarks_to_read

  # a trivially small success page which expects to be closed immediately
  # by the plugin
  get "bookmarks/success", controller: :bookmarks, action: :success, as: :bookmarks_success
  get "bookmarks/:id/archive", controller: :bookmarks, action: :archive, as: :bookmarks_archive, via: [:post, :put]

  resources :bookmarks do
    member do
      put "archive"
      get "download"
      put "mark_as_read"
      put "mark_to_read"
    end
  end

  resources :settings
  resources :tags

  get "importer", controller: :importer, action: :index, as: :importer_form
  post "importer/import", controller: :importer, action: :import, as: :importer_import


  # Defines the root path route ("/")
  root "bookmarks#index"


  match "/debugging/echo" => "debugging#echo", via: [:get, :post, :put, :patch, :delete]
end

app/models/setting.rb
class Setting
  include Mongoid::Document
  include Mongoid::Timestamps

  VALID_VALUE_CLASSES = Set.new([TrueClass, FalseClass, Integer, String, Array, Hash]).freeze

  field :lookup_key,  type:    String
  field :summary,     type:    String
  field :description, type:    String
  field :value
  field :visible,     type:    Boolean, default: false

  validates :lookup_key, :summary, :description, presence: true
  validates :lookup_key, uniqueness: true
  validate :valid_value

  def is_boolean?
    [TrueClass, FalseClass].include? value.class
  end

  private

  def valid_value
    # ok, value.class gets converted to a BSON::Document
    # but it LOOKS like a normal Hash, or whatever, when you
    # inspect it. So, that's why this is so funky
    unless VALID_VALUE_CLASSES.any? { |klass| value.is_a?(klass) }
      errors.add(:value, I18n.t("settings.errors.unsupported_value_type", type: value.class.name))
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_admin_enabled
  before_action :set_setting, only: %i[show edit update destroy]

  # GET /settings or /settings.json
  def index
    @settings = if !@setting_administration_enabled
      Setting.where(visible: true).order([:lookup_key, :asc])
    else
      Setting.order([:lookup_key, :asc])
    end
  end

  # GET /settings/1 or /settings/1.json
  def show
  end

  # NOTE: More security could be added,
  # but there's not really a point.
  # You can't see ANY of these endpoints if you're
  # not logged in, and if you really want to
  # create a setting that nothing uses,
  # or muck with the value of an existing one,
  # well… it's YOUR instance. You won't hurt
  # anyone else & you probably won't hurt your
  # data.

  # GET /settings/new
  def new
    @setting = Setting.new(value: {value: nil})
  end

  # GET /settings/1/edit
  def edit
  end

  # PATCH/PUT /settings/1 or /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(clean_params(setting_params))
        helpers.bust_settings_cache
        flash_message(:notice, I18n.t("settings.update_success"))
        format.html { redirect_to settings_url }
        format.json { render :show, status: :ok, location: @setting }
      else
        flash_message(:error, I18n.t("settings.errors.update_error"))
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    rescue JSON::ParserError
      flash_message(:error, I18n.t("settings.errors.invalid_json"))
      format.html { redirect_to edit_setting_url(@setting) }
      format.json { render json: @setting.errors, status: :unprocessable_entity }
    end
  end

  # DELETE /settings/1 or /settings/1.json
  def destroy
    @setting.destroy

    respond_to do |format|
      format.html { redirect_to settings_url, notice: I18n.t("deletion_success") }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_setting
    @setting = Setting.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def setting_params
    params.require(:setting).permit(:lookup_key, :summary, :description, :value, :value_type)
  end

  def clean_params(params_hash)
    cleaned_value = if params_hash[:value].present?
      if @setting.is_boolean?
        params_hash[:value] = params_hash[:value] == "true"
      else
        JSON.parse(params_hash[:value].strip)
      end
    end
    params_hash[:value] = cleaned_value

    params_hash
  end

  # 🤫 Sssshhhh is secret 1337 k0ntrol! No tell secret!
  def set_admin_enabled
    @setting_administration_enabled = ENV.fetch("ENABLE_SETTINGS_ADMINISTRATION", "false") == "true"
  end
end

app/views/settings/_form.html.erb
<%= form_with(model: setting) do |form| %>

  <div class="container">
  <% if @setting_administration_enabled %>

    <div class="row">
      <div class="col-2">
        <%= form.label :lookup_key, style: "display: block" %>
      </div>
      <div class="col">
        <%= form.text_field :lookup_key, dir: "auto" %>
      </div>
    </div>

    <div class="row">
      <div class="col-2">
        <%= form.label :summary, style: "display: block" %>
      </div>
      <div class="col">
        <%= form.text_field :summary %>
      </div>
    </div>

    <div class="row">
      <div class="col-2">
        <%= form.label :description, style: "display: block" %>
      </div>
      <div class="col">
        <%= form.text_area :description,
            cols: 60,
            rows: text_area_rows(setting.description, minimum: 4),
            dir: "auto" %>
      </div>
    </div>

    <% else
# setting administration disabled
       %>
    <div class="row">
      <div class="col">
        <%= t('settings.lookup_key') %>
      </div>
      <div class="col">
        <%= setting.lookup_key %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= t('settings.summary') %>
      </div>
      <div class="col">
        <%= setting.summary %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= t('settings.description') %>
      </div>
      <div class="col">
        <p>
          <%= setting.description %>
        </p>
      </div>
    </div>

    <% end %>

    <div class="row">
      <div class="col-2">
        <% if setting.is_boolean? %>
          <%= form.label :value,
              style: "display: block",
              "aria-label": t('settings.enable_disable_toggle_label')
              %>
        <% else %>
          <%= form.label :value, style: "display: block" %>
        <% end %>

      </div>
      <% if setting.is_boolean? %>
        <div class="col-2">
          <span class="form-check form-switch">
            <%= form.check_box :value,
                {
                  class: 'bookmark-checkbox-field form-check-input toggle',
                  role: "switch",
                  checked: setting.value
                },
                "true", "false"
                %>
          </span>
      <% else %>
        <div class="col">
          <div class="metadata"><%= t("settings.form.json_instructions") %></div>
          <%= form.text_area :value,
              value: setting.value.to_json,
              cols: 60,
              rows: text_area_rows(setting.value),
              dir: "auto" %>
      <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= form.submit class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/settings/_setting.html.erb
<div id="<%= dom_id setting %>">
  <p>
    <strong>Lookup key:</strong>
    <%= setting.lookup_key %>
  </p>

  <p>
    <strong>Summary:</strong>
    <%= setting.summary %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= setting.description %>
  </p>

  <p>
    <strong>Value:</strong>
    <%= setting.get_value %>
  </p>

</div>

app/views/settings/edit.html.erb
<h1>Editing setting</h1>

<%= render "form", setting: @setting %>

<br>

<div>
  <%= link_to "Show this setting", @setting %> |
  <%= link_to "Back to settings", settings_path %>
</div>

app/views/settings/index.html.erb
<div class="container">
  <div class="row">
    <div class="col"><h3 class='stylized-header'>Settings</h3></div>
  </div>
  <% if @setting_administration_enabled %>
  <div class="row mini-nav-links">
    <div class="col">
      <%= link_to t('settings.create_link'), new_setting_path %>
    </div>
  </div>
  <% end %>
</div>
<div id="settings" class="container tableish">

  <% if @settings.count > 0 %>
    <div class="row">
      <div class="col-1">&nbsp;</div>
      <div class="col-3"><%= t('settings.lookup_key') %></div>
      <div class="col"><%= t('settings.summary') %></div>
    </div>
    <% @settings.each do |setting| %>
      <div class="row">
        <div class="col-1">
          <%= icon_link("edit", edit_setting_path(setting),
              link_css: "inline-link-icon edit-link-icon",
              method: :put,
              text: nil) %>
        </div>
        <div class="col-3">
          <%= setting.lookup_key %>
        </div>
        <div class="col">
          <%= setting.summary %>
        </div>
      </div>
      <div class="row">
        <div class="col-1">&nbsp;</div>
        <div class="col-2">
          <%= t("settings.value") %> »
        </div>
        <div class="col">
          <%=setting.value %>
        </div>
      </div>
    <% end %>

  <% else %>
    <div class="row">
      <div class="col">
        <%== t('settings.no_settings_text') %>
      </div>
    </div>
  <% end %>
</div>

app/views/settings/new.html.erb
<h1>New setting</h1>

<%= render "form", setting: @setting %>

<br>

<div>
  <%= link_to "Back to settings", settings_path %>
</div>

app/views/settings/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
        <h3><%= @setting.lookup_key %>

          <% if @setting.visible || @setting_administration_enabled %>
            <%= icon_link("edit", edit_setting_path(@setting),
                link_css: "inline-link-icon edit-link-icon",
                method: :put,
                alt: t('settings.edit_icon_alt'),
                text: nil) %>
          <% end %>
        </h3>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= ::Rendering::Markdown.instance.render(@setting.summary.to_s).html_safe %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= ::Rendering::Markdown.instance.render(@setting.description.to_s).html_safe %>
    </div>
  </div>
  <div class="row">
    <div class="col heading">
      <h4>Value</h4>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <pre><tt><%= @setting.value %></tt></pre>
    </div>
  </div>
  <div class="row submit_div">
    <div class="col">
      <%= button_to "Destroy this setting", @setting, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: 'btn btn-danger' %>
    </div>
  </div>
</div>