config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "bookmarks/search", controller: :bookmarks, action: :search, as: :bookmarks_search
  get "bookmarks/tagged_with/:tags", controller: :bookmarks, action: :tagged_with, as: :bookmarks_tagged_with
  get "bookmarks/unarchived", controller: :bookmarks, action: :unarchived, as: :bookmarks_unarchived
  get "bookmarks/to_read", controller: :bookmarks, action: :to_read, as: :bookmarks_to_read

  # a trivially small success page which expects to be closed immediately
  # by the plugin
  get "bookmarks/success", controller: :bookmarks, action: :success, as: :bookmarks_success
  get "bookmarks/:id/archive", controller: :bookmarks, action: :archive, as: :bookmarks_archive, via: [:post, :put]

  resources :bookmarks do
    member do
      put "archive"
      get "download"
      put "mark_as_read"
      put "mark_to_read"
    end
  end

  resources :settings
  resources :tags

  get "importer", controller: :importer, action: :index, as: :importer_form
  post "importer/import", controller: :importer, action: :import, as: :importer_import


  # Defines the root path route ("/")
  root "bookmarks#index"


  match "/debugging/echo" => "debugging#echo", via: [:get, :post, :put, :patch, :delete]
end

app/models/tag.rb
class Tag
  include Mongoid::Document
  include Mongoid::Timestamps
  include BackupBrain::HtmlEntityEncoding

  field :name, type: String

  validates :name, presence:   true
  validates :name, uniqueness: true
  validate  :single_tag_only

  before_save :downcase_name
  before_destroy { |tag| Bookmark.remove_tag!(tag.name) }

  # BEGIN CLASS METHODS
  class << self
    # splits a string of tags, downcases them,
    # replaces spaces with underscores, and returns an array
    def split_tags(tags)
      return [] if tags.blank?
      tags.strip.split(/,?\s+|,/)
        .compact_blank
        .uniq
        .map { |t| t.strip.downcase.gsub(/\s+/, "_") }
    end

    # @return Boolean - true or false  indicating if the array of
    #                    tag strings are all valid
    def valid_tags?(array_o_strings)
      valid_tags(array_o_strings).size == array_o_strings.size
    end

    # @return [Array[String]] - returns the subset of tag
    #                           strings that are valid
    def valid_tags(array_o_strings)
      array_o_strings.select { |t|
        t.present? && t.downcase == t && !/\s+/.match?(t)
      }
    end

    # recreates tags from source data
    def regenerate_all!
      all_source_tags = Bookmark.pluck(:tags).flatten.uniq
      # When we have new things with tags they'll be added
      # to all_source_tags

      all_tag_names = Tag.pluck(:name)
      missing_tags = all_source_tags - all_tag_names
      invalid_tag_names = missing_tags - valid_tags(missing_tags)
      if invalid_tag_names.size > 0
        raise BackupBrain::Errors::InvalidTag.new(
          I18n.t("tags.errors.invalid_tag_names", names: invalid_tag_names.join(", "))
        )
      end
      obsolete_tags = all_tag_names - all_source_tags
      # alas, "Transactions are not supported for the cluster: standalone topology"
      Tag.create_many_by_name(missing_tags)
      Tag.where(name: obsolete_tags).destroy_all
      true
    end

    def orphaned_tag_names
      all_tags = Tag.pluck(:name)

      used_tags = Bookmark
        .tagged_with_any(all_tags)
        .pluck(:tags)
        .flatten
        .uniq
      # add other taggable models as needed

      all_tags - used_tags
    end

    def ensure_no_orphans!
      # WARNING: this is one of those cases where we're doing
      # something that would never work at scale, but is
      # totally fine because it's a single user instance.
      # it runs too many times, and it performs a deletion
      orphans = orphaned_tag_names
      return 0 if orphans.empty?
      Tag.where(:name.in => orphans).destroy_all
    end

    # compares the provided tag names to the
    # existing tags and creates any new ones that are
    # missing - skips callbacks
    def create_many_by_name_if_needed(names)
      return if names.empty?
      extant_tags = Tag.where(:name.in => names).pluck(:name)
      missing = names - extant_tags
      Tag.create_many_by_name(missing)
    end

    # Inserts many new tag objects WITHOUT callbacks or uniqueness validation
    def create_many_by_name(names)
      raise "can't create many tags because some are invalid" unless valid_tags? names
      return true if names.empty?
      Tag.collection.insert_many(names.map { |n| {name: n} })
    end

    def delete_orphaned_tags!
      bookmark_tags = Bookmark.pluck(:tags).flatten.uniq
      # Insert tags of other models here
      extant_tags = Tag.where(:name.in => names).pluck(:name)

      orphaned_tags = extant_tags - bookmark_tags
      Tag.where(:name.in => orphaned_tags).destroy_all
    end
  end

  # END CLASS METHODS

  def rename!(new_name)
    existing_tag = Tag.where(name: encode_unless_encoded(new_name)).first
    old_name  = name.dup
    if !existing_tag
      self.name = new_name
      save! # don't proceed if this doesn't work
    else
      destroy! # dun dun DUUUUNNNNN!
    end

    # Yes, this is less efficient than
    # just using has_and_belongs_to_many
    # See Bookmark#update_central_tags_list
    # for why it is this way.

    # NOTE: replace will handle deletion just fine
    Bookmark.replace_tag!(old_name, new_name)
    # INSERT OTHER TAGGABLE MODELS HERE
  end

  private

  # THOU SHALT NOT USE UPPER CASE IN THINE TAGS!!! 😉
  def downcase_name
    name&.downcase
  end

  def single_tag_only
    if Tag.split_tags(name).size != 1
      errors.add(:name, I18n.t("tags.errors.invalid_tag_name"))
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tag, only: %i[show edit update destroy]

  # GET /tags or /tags.json
  def index
    @starting_with = params[:starting_with]
    @tags = Tag.order([:name, :asc])
    # get all possible first chars
    @tags_first_characters = @tags.map { |t| t.name[0] }.uniq
    # then narrow it down to what was requested (if anything)
    if @starting_with
      regexp_char = /\w/.match?(@starting_with) ? @starting_with : "\\#{@starting_with}"
      @tags = @tags.where(name: /^#{regexp_char}/)
    end
  end

  # GET /tags/1 or /tags/1.json
  def show
  end

  # No direct creation of tags
  def new
    redirect_to tags_url
  end
  # NOTE: More security could be added,
  # but there's not really a point.
  # You can't see ANY of these endpoints if you're
  # not logged in, and if you really want to
  # create a tag that nothing uses,
  # or muck with the value of an existing one,
  # well… it's YOUR instance. You won't hurt
  # anyone else & you probably won't hurt your
  # data.

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    redirect_to tags_url
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    downcased = tag_params[:name].downcase
    respond_to do |format|
      if @tag.name == downcased || @tag.rename!(downcased)
        # renaming can result in deletion
        # because renaming it to match an existing one deletes the
        # one that got rename.
        if Tag.where(id: @tag.id).count > 0
          flash_message(:notice, I18n.t("tags.update_success"))
        else
          flash_message(:notice, I18n.t("tags.rename_deletion"))
        end
        format.html { redirect_to tags_url }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { redirect_to tags_url(@tag) }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url, notice: I18n.t("deletion_success") }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/views/tags/_form.html.erb
<%= form_with(model: tag) do |form| %>
  <div class="container">
    <div class="row">
      <div class="col-2">
      <%= form.label :name, style: "display: block" %>
      </div>
      <div class="col">
      <%= form.text_field :name, dir: "auto", value: tag.name.html_safe %>
      </div>
    </div>


    <div class="row">
      <div class="col">
        <%= form.submit class: 'btn btn-primary' %>

      </div>
    </div>
  </div>
<% end %>
<% content_for :sidebar do %>
  <%= render partial: 'shared/sidebar_page_actions_top' %>
  <div id="page-actions">
    <div class="container">
      <div class="row">
        <div class="col">
          <div class="safe-space">
            <%= button_to t('tags.destroy_link'), @tag,
                method: :delete ,
                class: 'btn btn-danger compact-button'%>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/tags/_setting.html.erb
<div id="<%= dom_id tag %>">
  <p>
    <strong>Lookup key:</strong>
    <%= tag.lookup_key %>
  </p>

  <p>
    <strong>Summary:</strong>
    <%= tag.summary %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= tag.description %>
  </p>

  <p>
    <strong>Value:</strong>
    <%= tag.value %>
  </p>

</div>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render "form", tag: @tag %>

<br>

<div>
  <%= link_to "Show this tag", @tag %> |
  <%= link_to "Back to tags", tags_path %>
</div>

app/views/tags/index.html.erb
<div class="container">
  <div class="row">
    <div class="col"><h3 class='stylized-header'><%= link_to(t('tags.list_heading'), tags_path()) %></h3></div>
  </div>
</div>
<div id="tags" class="container">

  <% if @tags.count > 0 %>
    <div class="row">
      <div class="col">
        <nav class="pagy-bootstrap-nav" role="navigation">
        <ul class="pagination tag-admin-list">
        <% @tags_first_characters.each do | char | %>
          <li class="page-item<% if @starting_with == char %> active<% end %>">
            <%= link_to(char, tags_path(starting_with: char),
                class: "page-link tags-page-link"
                ) %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
      <div class="row">
        <div class="col">
          <ul class="admin-tags-list">
    <% @tags.each do |tag| %>
          <li>
          <%= icon_link("edit", edit_tag_path(tag),
              link_css: "inline-link-icon edit-link-icon",
              method: :put,
              text: nil) %>
            <%= link_to(tag.name.html_safe, bookmarks_tagged_with_path(tags: tag.name)) %>

          </li>
    <% end %>
          </li>
        </div>
      </div>

  <% else %>
    <div class="row">
      <div class="col">
        <%== t('tags.no_tags_text') %>
      </div>
    </div>
  <% end %>
</div>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render "form", tag: @tag %>

<br>

<div>
  <%= link_to "Back to tags", tags_path %>
</div>

app/views/tags/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
        <h3><%= @tag.lookup_key %>

          <% if @tag.visible || @tag_administration_enabled %>
            <%= icon_link("edit", edit_tag_path(@tag),
                link_css: "inline-link-icon edit-link-icon",
                method: :put,
                alt: t('tags.edit_icon_alt'),
                text: nil) %>
          <% end %>
        </h3>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= ::Rendering::Markdown.instance.render(@tag.summary.to_s).html_safe %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= ::Rendering::Markdown.instance.render(@tag.description.to_s).html_safe %>
    </div>
  </div>
  <div class="row">
    <div class="col heading">
      <h4>Value</h4>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <pre><tt><%= @tag.inner_value %></tt></pre>
    </div>
  </div>
  <div class="row submit_div">
    <div class="col">
      <%= button_to "Destroy this tag", @tag, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: 'btn btn-danger' %>
    </div>
  </div>
</div>